#%RAML 1.0 DataType
---
displayName: ActivityFeed
type: object
description: The activity feed for a candidate.
properties:
  notes:
    type: array #!include ActivityFeedNote.raml
  emails:
    type: array #!include ActivityFeedEmail.raml
  activities:
    type: array #!include ActivityFeedActivity.raml
