#%RAML 1.0 DataType
---
displayName: CreditedTo
type: object
description: The employee credited for a referral.
properties:
  id?:
    type: integer
    description: The ID of the referrer this token is credited to.
  name:
    description: The full name of the credited referrer.
    type: string
  employee_id?:
    description: The Referrer's External/Employee ID
    type: string
