#%RAML 1.0 DataType
displayName: KeyedCustomField
type: object
description:
  A Keyed Custom Field is a user-defined special field that can be used to store additional data about a Greenhouse object,
  such as job or application, but stores additional metadata about each field. This contains the same information as custom_fields
  but formatted in a different way that includes more information. This will tell you the type of custom field data to expect,
  the text name of custom field, and the value. The key of this hash is the custom field’s immutable field key, which will not
  change even if the name of the custom field is changed in Greenhouse.
additionalProperties: true
example: !include ../examples/v1/keyed_custom_field.json
