#%RAML 1.0 DataType
displayName: PostCandidate
type: object
description: A Candidate is a person who is either a prospect for a job or has an application for a job.
uses:
  Harvest: types.raml
properties:
  first_name: string
  last_name: string
  company?: string
  title?: string
  is_private?: boolean
  applications?: array
  phone_numbers?: Harvest.PhoneNumber[]
  addresses?: Harvest.Address[]
  email_addresses?: Harvest.EmailAddress[]
  website_addresses?: Harvest.WebsiteAddress[]
  social_media_addresses?: Harvest.SocialMediaAddress[]
  tags?: string[]
  custom_fields?: Harvest.CustomField[]
  recruiter:
    type: object
    required: false
    properties:
      id: number
      email: string
  coordinator:
    type: object
    required: false
    properties:
      id: number
      email: string
  activity_feed_notes?: Harvest.ActivityFeedNote[]
example: !include ../examples/v1/post_candidate.json
