#%RAML 1.0 DataType
displayName: Recruiter
type: object
description: A Recruiter is a user in Greenhouse who is responsible for recruiting and managing candidates/applications.
properties:
  id: number
  name: string
