#%RAML 1.0 DataType
displayName: RejectionReason
description: Why a candidate got rejected
type: object
properties:
  id: number
  name: string
  type:
    type: object
    properties:
      id: number
      name: string
