#%RAML 1.0 DataType
---
displayName: Source
type: object
description: The source of the job post referral link.
properties:
  id:
    description: The ID of the source for this token.
    type: integer
  public_name:
    description: The public name used for this particular source.
    type: string
