#%RAML 1.0 Library
usage: |
  Use to define some standard complex Harvest data types.
types:
  ActivityFeedActivity: !include ActivityFeedActivity.raml
  ActivityFeedEmail: !include ActivityFeedEmail.raml
  ActivityFeedNote: !include ActivityFeedNote.raml
  Answer: !include Answer.raml
  CreditedTo: !include CreditedTo.raml
  JobStage: !include JobStage.raml
  RejectionReason: !include RejectionReason.raml
  SimpleJob: !include SimpleJob.raml
  Source: !include Source.raml
  TrackingLink: !include TrackingLink.raml
  User: !include User.raml
