#%RAML 1.0 Library
usage: |
  Use to define some standard complex Harvest data types.
types:
  ActivityFeedActivity: !include ActivityFeedActivity.raml
  ActivityFeedEmail: !include ActivityFeedEmail.raml
  ActivityFeedNote: !include ActivityFeedNote.raml
  Address: !include Address.raml
  Answer: !include Answer.raml
  Attachment: !include Attachment.raml
  CreditedTo: !include CreditedTo.raml
  CustomField: !include CustomField.raml
  Department: !include Department.raml
  EmailAddress: !include EmailAddress.raml
  JobStage: !include JobStage.raml
  KeyedCustomField: !include KeyedCustomField.raml
  PhoneNumber: !include PhoneNumber.raml
  PostActivityFeedNote: !include PostActivityFeedNote.raml
  PostCandidateApplication: !include PostCandidateApplication.raml
  Recruiter: !include Recruiter.raml
  RejectionReason: !include RejectionReason.raml
  SimpleAttachment: !include SimpleAttachment.raml
  SimpleJob: !include SimpleJob.raml
  SocialMediaAddress: !include SocialMediaAddress.raml
  Source: !include Source.raml
  Tag: !include Tag.raml
  TrackingLink: !include TrackingLink.raml
  User: !include User.raml
  WebsiteAddress: !include WebsiteAddress.raml
