#%RAML 1.0
---
title: Harvest API
baseUri: https://harvest.greenhouse.io/{version}
version: v1
uses:
  Harvest: types/types.raml
documentation:
  - title: Introduction
    content: !include pages/introduction.md
  - title: Authentication
    content: !include pages/authentication.md
  - title: Throttling
    content: !include pages/throttling.md
  - title: Pagination
    content: !include pages/pagination.md
  - title: Validation
    content: !include pages/validation.md
  - title: General Considerations
    content: !include pages/general_considerations.md
  - title: Errors
    content: !include pages/errors.md
mediaType: application/json
securedBy: apiKeyAuth
securitySchemes:
  apiKeyAuth:
    description: Each request must contain the API key as the username with a blank password; the whole thing must be Base64 encoded.
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64 encoded "{API Key}:"
                       credentials.
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.
types:
  TrackingLink: !include types/TrackingLink.raml
  ActivityFeed: !include types/ActivityFeed.raml
  Application: !include types/Application.raml
  Candidate: !include types/Candidate.raml
  PatchCandidate: !include types/PatchCandidate.raml
  PostCandidate: !include types/PostCandidate.raml
traits:
  auditable:
    headers:
      On-Behalf-Of:
        type: integer
        description: ID of the user issuing this request. Required for auditing purposes.
  pageable:
    queryParameters:
      per_page?: number
      page?: number
    responses:
      200:
        headers:
          Link:
            type: string
            example: !include examples/v1/link.txt
  updatedFilterable:
    queryParameters:
      updated_before?: datetime-only
      updated_after?: datetime-only
  createdFilterable:
    queryParameters:
      created_before?: datetime-only
      created_after?: datetime-only
  jobFilterable:
    queryParameters:
      job_id?: number
  candidateIdable:
    queryParameters:
      id:
        type: number
        description: The ID of the candidate
        required: true
/applications: !include ./endpoints/applications.raml
/candidates: !include ./endpoints/candidates.raml
/jobs: !include ./endpoints/jobs.raml
/prospects: !include ./endpoints/prospects.raml
/departments: !include ./endpoints/departments.raml
